name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:  # Allow manual triggering
    inputs:
      branchname:    
        required: true
        default: 'release-**'
  push:
    branches:
      -'release-**'
jobs:
  list-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v3

      - name: List all PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
          | jq '.[] | {title: .title, head: .head.ref, base: .base.ref, body: .body}'
permissions:
  contents: read
  pull-requests: read